=== Ladrys/webdesign/API/json-schema/event.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "id",
    "name",
    "theme",
    "description",
    "date",
    "startTime",
    "endTime",
    "dayId",
    "venueId",
    "venueName",
    "performerIds",
    "performers",
    "highlight"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "theme": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "date": {
      "type": "string",
      "format": "date"
    },
    "startTime": {
      "type": "string"
    },
    "endTime": {
      "type": "string"
    },
    "dayId": {
      "type": "string"
    },
    "venueId": {
      "type": "string"
    },
    "venueName": {
      "type": "string"
    },
    "performerIds": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "performers": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "highlight": {
      "type": "boolean"
    }
  }
}

=== Ladrys/webdesign/API/json/event-a1.json
{"id":"a1","name":"Tiësto","theme":"Progressive house","description":"Nizozemský DJ a producent s kořeny v trance. Postupně rozšířil svůj zvuk o house a další podoby taneční elektroniky. Pochází z nizozemské Bredy.","date":"2027-08-01","startTime":"12:30:00","endTime":"13:30:00","highlight":false,"dayId":"d1","venueId":"h1","venueName":"Main Hall","performerIds":["i4"],"performers":["Tiësto"]}
